package dataprocessing;


/**
* dataprocessing/dblp_Data.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from hw2.idl
* Thursday, October 15, 2020 1:50:26 PM CDT
*/

public interface dblp_Data extends dblp_DataOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface dblp_Data
