package dataprocessing;


import java.io.IOException;

/**
* dataprocessing/dblp_DataOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from hw2.idl
* Thursday, October 15, 2020 1:50:26 PM CDT
*/

public interface dblp_DataOperations 
{
  String sayhello ();
  String one_author ();
  String author_no_intereption () throws IOException;
  String top_100 ();
  String top_100_co_authors ();
} // interface dblp_DataOperations
