package dataprocessing;

/**
* dataprocessing/dblp_DataHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from hw2.idl
* Thursday, October 15, 2020 1:50:26 PM CDT
*/

public final class dblp_DataHolder implements org.omg.CORBA.portable.Streamable
{
  public dataprocessing.dblp_Data value = null;

  public dblp_DataHolder ()
  {
  }

  public dblp_DataHolder (dataprocessing.dblp_Data initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = dataprocessing.dblp_DataHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    dataprocessing.dblp_DataHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return dataprocessing.dblp_DataHelper.type ();
  }

}
